baseURL: https://salastro.github.io

languageCode: en-us
title: "SalahDin Ahmed"
theme: "toha-improved"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  description: "My place for dumping stuff."
  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/salastro/salastro.github.io
  gitBranch: master

  # Background image of the landing page
  background: /images/site/background.jpg

  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    # portfolio:
    #   enable: true
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        reddit: true
        linkedin: true
        mastodon: true

    # Enable Analytics
    analytics:
      enabled: true
      # GoatCounter
      goatCounter:
        code: salastro
      # CounterDev
      counterDev:
        id: salastro

    comment:
      enable: true
      giscus:
        repo: salastro/salastro.github.io
        repoID: MDEwOlJlcG9zaXRvcnkzODAwNDc0NDg=
        category: Announcements
        categoryID: DIC_kwDOFqcQWM4COLPr
        theme: dark
        map: title
        reaction: 1
        metadata: 0
        inputPosition: top
        # loading: lazy
        crossOrigin: anonymous

    # Enable Support
    # support:
    #   enabled: true
    #   kofi:
    #     user: salastro
    #     text: Buy me coffee
    #     textColor: '#f9fafc'
    #     backgroundColor: '#248aaa'

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true
  # enableTags: true

  footer:
    enable: false
